run:
  timeout: 5m
linters:
  enable:
    - megacheck
    - revive
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - unconvert
    - dupl
    - nakedret
    - prealloc
    - exportloopref
    - depguard
    - importas
    - nolintlint
    - unconvert
    # auto-fix
    - godot
    - gofmt
    - gofumpt
    - goimports
    - misspell
    - whitespace
    # test
    - testpackage
    - tenv
    # - thelper
  # disabled because of go1.18
  # track go1.18 support at
  # https://github.com/golangci/golangci-lint/issues/2649
  disable:
    - structcheck
