on:
  push:
    branches:
      - main
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get-tag
        run: echo "::set-output name=tag::$(git rev-parse --short ${{ github.sha }})"
      - id: build-push
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=registry,ref=frantjc/sequence:latest
          cache-to: type=inline
          build-args: |
            tag=${{ steps.get-tag.outputs.tag }}
            commit=${{ github.sha }}
          tags: frantjc/sequence:${{ steps.get-tag.outputs.tag }}
