on:
  push:
    branches:
      - main
jobs:
  check-composite-order:
    runs-on: ubuntu-latest
    steps:
      - uses: frantjc/sequence/testdata/actions/docker@main
      - uses: frantjc/sequence/testdata/actions/composite@main
