on:
  push:
    tags:
      - v*
permissions: 
  contents: read
  packages: write 
jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get-tag
        id: get-tag
        run: |
          echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"
      - uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            version=${{ steps.get-tag.outputs.tag }}
          tags: |
            ghcr.io/${{ github.repository }}
            ghcr.io/${{ github.repository }}:${{ steps.get-tag.outputs.tag }}
  release-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
